# Generated by Django 6.0.5 on 2026-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pollingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingunit',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
